### ISSUE TITLE
snorkel.add-user fails

### ISSUE THREAD

**Issue by niteria** [logv/snorkel#41]
I installed snorkel via snap. I get:

```
$ snorkel.add-user niteria
SNAP DIR: /home/niteria/snap/snorkel/common
net.js:10
const cares = process.binding('cares_wrap');
                      ^

Error: EFILE
    at Error (native)
    at net.js:10:23
    at NativeModule.compile (bootstrap_node.js:496:7)
    at NativeModule.require (bootstrap_node.js:437:18)
    at internal/child_process.js:6:13
    at NativeModule.compile (bootstrap_node.js:496:7)
    at NativeModule.require (bootstrap_node.js:437:18)
    at child_process.js:12:23
    at NativeModule.compile (bootstrap_node.js:496:7)
    at Function.NativeModule.require (bootstrap_node.js:437:18)
```

I was able to work around it by:
```
cd ~/snap/snorkel/common
/snap/snorkel/12/lib/node_modules/snorkel/scripts/add_user.sh niteria
```

**Comment by okayzed** [comment]
hi @niteria,

  thanks for reporting, i will look into this and try to figure out whats going wrong and upload a new snap. please let me know any other issues or feature requests you have. 

  because of the difficulties i've had with creating a stable deploy in the rapidly changing node / npm ecosystem,  i have been working on a python based snorkel that re-uses the current front end JS code (but python in the web backend instead of node). i have been using it locally for a few weeks now, but the plan is to release it next year (in or after january 2018).

**Comment by okayzed** [comment]
I've uploaded a more recent snap and downloaded / re-installed it and am able to run snorkel.add-user. When I used the 0.3.2 release, I received the same error as you, now I do not receive that error.

If this doesn't fix it, I will continue investigating

**Comment by okayzed** [comment]
after waking up and having some more coffee, I don't think it works after all, I think it just fails more silently.

**Comment by niteria** [comment]
Hi @okayzed,

Thanks for the quick response and thanks for letting me know about future plans.
I've found a workaround, so it's not a hi-pri for me and it looks like this code will disappear soon.
I wouldn't mind if you #wontfixed it.

Btw this project is awesome, I miss using Scuba, I'm impressed how much feature parity there is.

**Comment by okayzed** [comment]
thank you! and closing for now
